[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor_mint_sell_nft = "BPoaUKQYHasHr1Zx4ZLLTTMqezWbKKTgBFZv9LDK8drZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/air/.config/solana/devnet.json"

[scripts]
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
test-mint-spltoken = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint-spltoken.ts"
test-sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-sell.ts"

